package com.oc.dao;

import com.oc.entity.CourseVideo;
import com.oc.entity.CourseVideo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(CourseVideo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(CourseVideo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<CourseVideo> selectBy(CourseVideo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    CourseVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") CourseVideo record, @Param("example") CourseVideo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") CourseVideo record, @Param("example") CourseVideo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_VIDEO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(CourseVideo record);
}