package com.oc.dao;

import com.oc.entity.CourseTeacher;
import com.oc.entity.CourseTeacher;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(CourseTeacher example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(CourseTeacher example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(CourseTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(CourseTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<CourseTeacher> selectBy(CourseTeacher example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    CourseTeacher selectByPrimaryKey(BigDecimal courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") CourseTeacher record, @Param("example") CourseTeacher example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") CourseTeacher record, @Param("example") CourseTeacher example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(CourseTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_TEACHER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(CourseTeacher record);
}