package com.oc.dao;

import java.util.List;

import com.oc.entity.CourseUserNote;
import com.oc.util.Page;

public interface CourseUserNoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_USER_NOTE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countByExample(CourseUserNote example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_USER_NOTE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByExample(CourseUserNote example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_USER_NOTE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(CourseUserNote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_USER_NOTE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<CourseUserNote> selectByExample(CourseUserNote example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_USER_NOTE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<CourseUserNote> findPage(Page<CourseUserNote> note );


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.COURSE_USER_NOTE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(CourseUserNote record);


}