package com.oc.dao;

import com.oc.entity.QuestionsClass;
import com.oc.entity.QuestionsClass;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionsClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(QuestionsClass example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(QuestionsClass example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(QuestionsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(QuestionsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<QuestionsClass> selectBy(QuestionsClass example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    QuestionsClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") QuestionsClass record, @Param("example") QuestionsClass example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") QuestionsClass record, @Param("example") QuestionsClass example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(QuestionsClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.QUESTIONS_CLASS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(QuestionsClass record);
}