package com.oc.dao;

import com.oc.entity.TabQuestions;
import com.oc.util.Page;
import com.oc.entity.TabQuestions;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabQuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countByExample(TabQuestions example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(TabQuestions example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(TabQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(TabQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<TabQuestions> selectBy(TabQuestions example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    TabQuestions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") TabQuestions record, @Param("example") TabQuestions example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") TabQuestions record, @Param("example") TabQuestions example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(TabQuestions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TAB_QUESTIONS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(TabQuestions record);

	List<TabQuestions> findPage(Page<TabQuestions> page);
}