package com.oc.dao;

import com.oc.entity.TeacherDegree;
import com.oc.entity.TeacherDegree;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherDegreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(TeacherDegree example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(TeacherDegree example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(TeacherDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(TeacherDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<TeacherDegree> selectBy(TeacherDegree example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    TeacherDegree selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") TeacherDegree record, @Param("example") TeacherDegree example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") TeacherDegree record, @Param("example") TeacherDegree example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(TeacherDegree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.TEACHER_DEGREE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(TeacherDegree record);
}