package com.oc.dao;

import com.oc.entity.UserInfo;
import com.oc.entity.UserInfo;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int countBy(UserInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int deleteBy(UserInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    List<UserInfo> selectByExample(UserInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    UserInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int updateBySelective(@Param("record") UserInfo record, @Param("example") UserInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int updateBy(@Param("record") UserInfo record, @Param("example") UserInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_INFO
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    int updateByPrimaryKey(UserInfo record);

}