package com.oc.dao;

import com.oc.entity.UserWords;
import com.oc.entity.UserWords;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserWordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(UserWords example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(UserWords example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(UserWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(UserWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<UserWords> selectByExample(UserWords example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    UserWords selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") UserWords record, @Param("example") UserWords example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") UserWords record, @Param("example") UserWords example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserWords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_WORDS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(UserWords record);
}