package com.oc.dao;

import com.oc.entity.UserHistorytestPaper;
import com.oc.entity.UserHistorytestPaper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserHistorytestPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(UserHistorytestPaper example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(UserHistorytestPaper example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(UserHistorytestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(UserHistorytestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<UserHistorytestPaper> selectBy(UserHistorytestPaper example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    UserHistorytestPaper selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") UserHistorytestPaper record, @Param("example") UserHistorytestPaper example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") UserHistorytestPaper record, @Param("example") UserHistorytestPaper example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserHistorytestPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_HISTORYTEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(UserHistorytestPaper record);
}