package com.oc.dao;

import com.oc.entity.UserVedio;
import com.oc.entity.UserVedio;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserVedioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countBy(UserVedio example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(UserVedio example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(UserVedio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(UserVedio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<UserVedio> selectBy(UserVedio example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    UserVedio selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") UserVedio record, @Param("example") UserVedio example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") UserVedio record, @Param("example") UserVedio example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserVedio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_VEDIO
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(UserVedio record);
}