package com.oc.dao;

import com.oc.entity.UserMood;
import com.oc.entity.UserMood;
import com.oc.util.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserMoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int countByExample(UserMood example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteBy(UserMood example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insert(UserMood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int insertSelective(UserMood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    List<UserMood> selectBy(UserMood example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    UserMood selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBySelective(@Param("record") UserMood record, @Param("example") UserMood example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateBy(@Param("record") UserMood record, @Param("example") UserMood example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKeySelective(UserMood record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ONLINECOURSE.USER_MOOD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    int updateByPrimaryKey(UserMood record);
    
	List<UserMood> findPage(Page<UserMood> page);
}