package com.oc.entity;

import java.util.Date;
import java.util.List;

public class CourseUserNote extends BaseEntity{

	private List<CourseUserNote> list;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.VEDIO_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer userId;

    private String houzhui;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.FILE_PATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.COURSE_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String courseName;

    
    private Integer vedioId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_USER_NOTE.VEDIO_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String vedioName;
    
    private String noteName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.ID
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

 
   

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.VEDIO_ID
     *
     * @param id the value for ONLINECOURSE.COURSE_USER_NOTE.VEDIO_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.USER_ID
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.USER_ID
     *
     * @param userId the value for ONLINECOURSE.COURSE_USER_NOTE.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.FILE_PATH
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.FILE_PATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.FILE_PATH
     *
     * @param filePath the value for ONLINECOURSE.COURSE_USER_NOTE.FILE_PATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.COURSE_USER_NOTE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.UPDATE_DATE
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.UPDATE_DATE
     *
     * @param updateDate the value for ONLINECOURSE.COURSE_USER_NOTE.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.COURSE_NAME
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.COURSE_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.COURSE_NAME
     *
     * @param courseName the value for ONLINECOURSE.COURSE_USER_NOTE.COURSE_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_USER_NOTE.VEDIO_NAME
     *
     * @return the value of ONLINECOURSE.COURSE_USER_NOTE.VEDIO_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getVedioName() {
        return vedioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_USER_NOTE.VEDIO_NAME
     *
     * @param vedioName the value for ONLINECOURSE.COURSE_USER_NOTE.VEDIO_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setVedioName(String vedioName) {
        this.vedioName = vedioName == null ? null : vedioName.trim();
    }




	public String getNoteName() {
		return noteName;
	}




	public void setNoteName(String noteName) {
		this.noteName = noteName;
	}




	public List<CourseUserNote> getList() {
		return list;
	}




	public void setList(List<CourseUserNote> list) {
		this.list = list;
	}




	public Integer getVedioId() {
		return vedioId;
	}




	public void setVedioId(Integer vedioId) {
		this.vedioId = vedioId;
	}




	public String getHouzhui() {
		return houzhui;
	}




	public void setHouzhui(String houzhui) {
		this.houzhui = houzhui;
	}
    
}