package com.oc.entity;


public class Course extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.CLASS_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.COURSE_COVER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String courseCover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.COURSE_SUMMARY
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String courseSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.CERTIFICATE_REQUIREMENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String certificateRequirement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.KNOWLEDGE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String knowledge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.OUTLINE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String outline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.REMARKS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.ID
     *
     * @return the value of ONLINECOURSE.COURSE.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.ID
     *
     * @param id the value for ONLINECOURSE.COURSE.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.NAME
     *
     * @return the value of ONLINECOURSE.COURSE.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.NAME
     *
     * @param name the value for ONLINECOURSE.COURSE.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.CLASS_ID
     *
     * @return the value of ONLINECOURSE.COURSE.CLASS_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.CLASS_ID
     *
     * @param classId the value for ONLINECOURSE.COURSE.CLASS_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.ISDELETE
     *
     * @return the value of ONLINECOURSE.COURSE.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.ISDELETE
     *
     * @param isdelete the value for ONLINECOURSE.COURSE.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.COURSE_COVER
     *
     * @return the value of ONLINECOURSE.COURSE.COURSE_COVER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getCourseCover() {
        return courseCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.COURSE_COVER
     *
     * @param courseCover the value for ONLINECOURSE.COURSE.COURSE_COVER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCourseCover(String courseCover) {
        this.courseCover = courseCover == null ? null : courseCover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.COURSE_SUMMARY
     *
     * @return the value of ONLINECOURSE.COURSE.COURSE_SUMMARY
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getCourseSummary() {
        return courseSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.COURSE_SUMMARY
     *
     * @param courseSummary the value for ONLINECOURSE.COURSE.COURSE_SUMMARY
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCourseSummary(String courseSummary) {
        this.courseSummary = courseSummary == null ? null : courseSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.CERTIFICATE_REQUIREMENT
     *
     * @return the value of ONLINECOURSE.COURSE.CERTIFICATE_REQUIREMENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getCertificateRequirement() {
        return certificateRequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.CERTIFICATE_REQUIREMENT
     *
     * @param certificateRequirement the value for ONLINECOURSE.COURSE.CERTIFICATE_REQUIREMENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCertificateRequirement(String certificateRequirement) {
        this.certificateRequirement = certificateRequirement == null ? null : certificateRequirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.KNOWLEDGE
     *
     * @return the value of ONLINECOURSE.COURSE.KNOWLEDGE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getKnowledge() {
        return knowledge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.KNOWLEDGE
     *
     * @param knowledge the value for ONLINECOURSE.COURSE.KNOWLEDGE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setKnowledge(String knowledge) {
        this.knowledge = knowledge == null ? null : knowledge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.OUTLINE
     *
     * @return the value of ONLINECOURSE.COURSE.OUTLINE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.OUTLINE
     *
     * @param outline the value for ONLINECOURSE.COURSE.OUTLINE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.REMARKS
     *
     * @return the value of ONLINECOURSE.COURSE.REMARKS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.REMARKS
     *
     * @param remarks the value for ONLINECOURSE.COURSE.REMARKS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.COURSE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.COURSE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}