package com.oc.entity;

import java.util.Date;

public class CourseVideo extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.VIDEOPATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String videopath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.CREATIME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Date creatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.VIDEOLONG
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer videolong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.TOTAL
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.COMMENT_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.COURSE_VIDEO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.ID
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.ID
     *
     * @param id the value for ONLINECOURSE.COURSE_VIDEO.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.COURSE_ID
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.COURSE_ID
     *
     * @param courseId the value for ONLINECOURSE.COURSE_VIDEO.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.VIDEOPATH
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.VIDEOPATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getVideopath() {
        return videopath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.VIDEOPATH
     *
     * @param videopath the value for ONLINECOURSE.COURSE_VIDEO.VIDEOPATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setVideopath(String videopath) {
        this.videopath = videopath == null ? null : videopath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.CREATIME
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.CREATIME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Date getCreatime() {
        return creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.CREATIME
     *
     * @param creatime the value for ONLINECOURSE.COURSE_VIDEO.CREATIME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCreatime(Date creatime) {
        this.creatime = creatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.VIDEOLONG
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.VIDEOLONG
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getVideolong() {
        return videolong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.VIDEOLONG
     *
     * @param videolong the value for ONLINECOURSE.COURSE_VIDEO.VIDEOLONG
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setVideolong(Integer videolong) {
        this.videolong = videolong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.TOTAL
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.TOTAL
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.TOTAL
     *
     * @param total the value for ONLINECOURSE.COURSE_VIDEO.TOTAL
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.COMMENT_COUNT
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.COMMENT_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.COMMENT_COUNT
     *
     * @param commentCount the value for ONLINECOURSE.COURSE_VIDEO.COMMENT_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.COURSE_VIDEO.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.COURSE_VIDEO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.COURSE_VIDEO.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.COURSE_VIDEO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}