package com.oc.entity;

public class QuestionsClass extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_CLASS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_CLASS.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_CLASS.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_CLASS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_CLASS.ID
     *
     * @return the value of ONLINECOURSE.QUESTIONS_CLASS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_CLASS.ID
     *
     * @param id the value for ONLINECOURSE.QUESTIONS_CLASS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_CLASS.NAME
     *
     * @return the value of ONLINECOURSE.QUESTIONS_CLASS.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_CLASS.NAME
     *
     * @param name the value for ONLINECOURSE.QUESTIONS_CLASS.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_CLASS.ISDELETE
     *
     * @return the value of ONLINECOURSE.QUESTIONS_CLASS.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_CLASS.ISDELETE
     *
     * @param isdelete the value for ONLINECOURSE.QUESTIONS_CLASS.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_CLASS.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.QUESTIONS_CLASS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_CLASS.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.QUESTIONS_CLASS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}