package com.oc.entity;

import java.util.Date;
import java.util.List;

public class QuestionsAnswer extends BaseEntity{
	
	private QuestionsAnswer  questionsAnswer;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.QUESTION_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.THUMBSUP_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer thumbsupCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.DESPISE_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer despiseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Date answerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.ISPUT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String answerName;

    private String answerContent;
    
    private Integer answerUserid;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ID
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ID
     *
     * @param id the value for ONLINECOURSE.QUESTIONS_ANSWER.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.QUESTION_ID
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.QUESTION_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.QUESTION_ID
     *
     * @param questionId the value for ONLINECOURSE.QUESTIONS_ANSWER.QUESTION_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_ID
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_ID
     *
     * @param answerId the value for ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.THUMBSUP_COUNT
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.THUMBSUP_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getThumbsupCount() {
        return thumbsupCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.THUMBSUP_COUNT
     *
     * @param thumbsupCount the value for ONLINECOURSE.QUESTIONS_ANSWER.THUMBSUP_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setThumbsupCount(Integer thumbsupCount) {
        this.thumbsupCount = thumbsupCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.DESPISE_COUNT
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.DESPISE_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getDespiseCount() {
        return despiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.DESPISE_COUNT
     *
     * @param despiseCount the value for ONLINECOURSE.QUESTIONS_ANSWER.DESPISE_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setDespiseCount(Integer despiseCount) {
        this.despiseCount = despiseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_DATE
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Date getAnswerDate() {
        return answerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_DATE
     *
     * @param answerDate the value for ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setAnswerDate(Date answerDate) {
        this.answerDate = answerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ISPUT
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.ISPUT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsput() {
        return isput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ISPUT
     *
     * @param isput the value for ONLINECOURSE.QUESTIONS_ANSWER.ISPUT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsput(Integer isput) {
        this.isput = isput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.QUESTIONS_ANSWER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_NAME
     *
     * @return the value of ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getAnswerName() {
        return answerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_NAME
     *
     * @param answerName the value for ONLINECOURSE.QUESTIONS_ANSWER.ANSWER_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setAnswerName(String answerName) {
        this.answerName = answerName == null ? null : answerName.trim();
    }

	public QuestionsAnswer getQuestionsAnswer() {
		return questionsAnswer;
	}

	public void setQuestionsAnswer(QuestionsAnswer questionsAnswer) {
		this.questionsAnswer = questionsAnswer;
	}

	public String getAnswerContent() {
		return answerContent;
	}

	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent;
	}

	public Integer getAnswerUserid() {
		return answerUserid;
	}

	public void setAnswerUserid(Integer answerUserid) {
		this.answerUserid = answerUserid;
	}
    
    
}