package com.oc.entity;

import java.util.Date;
import java.util.List;

/**
 * @author wang
 *
 */
public class TabQuestions extends BaseEntity{
	private List<TabQuestions> list;
	
	private List<QuestionsAnswer> questionsAnswers;  //问题回答
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.QUESTIONS_CLASS_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer questionsClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.FILE_PATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.DOUBT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String doubt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.CONTENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_QUESTIONS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;
    
    private Integer userId; 
    
    private UserInfo userinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.ID
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.ID
     *
     * @param id the value for ONLINECOURSE.TAB_QUESTIONS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.QUESTIONS_CLASS_ID
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.QUESTIONS_CLASS_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getQuestionsClassId() {
        return questionsClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.QUESTIONS_CLASS_ID
     *
     * @param questionsClassId the value for ONLINECOURSE.TAB_QUESTIONS.QUESTIONS_CLASS_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setQuestionsClassId(Integer questionsClassId) {
        this.questionsClassId = questionsClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.FILE_PATH
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.FILE_PATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.FILE_PATH
     *
     * @param filePath the value for ONLINECOURSE.TAB_QUESTIONS.FILE_PATH
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.DOUBT
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.DOUBT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getDoubt() {
        return doubt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.DOUBT
     *
     * @param doubt the value for ONLINECOURSE.TAB_QUESTIONS.DOUBT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setDoubt(String doubt) {
        this.doubt = doubt == null ? null : doubt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.CONTENT
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.CONTENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.CONTENT
     *
     * @param content the value for ONLINECOURSE.TAB_QUESTIONS.CONTENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.STATUS
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.STATUS
     *
     * @param status the value for ONLINECOURSE.TAB_QUESTIONS.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_QUESTIONS.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.TAB_QUESTIONS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_QUESTIONS.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.TAB_QUESTIONS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public List<TabQuestions> getList() {
		return list;
	}

	public void setList(List<TabQuestions> list) {
		this.list = list;
	}

	public Date getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public List<QuestionsAnswer> getQuestionsAnswers() {
		return questionsAnswers;
	}

	public void setQuestionsAnswers(List<QuestionsAnswer> questionsAnswers) {
		this.questionsAnswers = questionsAnswers;
	}

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}

	
	
}