package com.oc.entity;

public class TabSchool extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_SCHOOL.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_SCHOOL.SCHOOL_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_SCHOOL.IMAGE_SIZE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String imageSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_SCHOOL.SCHOOL_PROFILE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String schoolProfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_SCHOOL.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TAB_SCHOOL.PASSWORD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_SCHOOL.ID
     *
     * @return the value of ONLINECOURSE.TAB_SCHOOL.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_SCHOOL.ID
     *
     * @param id the value for ONLINECOURSE.TAB_SCHOOL.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_SCHOOL.SCHOOL_NAME
     *
     * @return the value of ONLINECOURSE.TAB_SCHOOL.SCHOOL_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_SCHOOL.SCHOOL_NAME
     *
     * @param schoolName the value for ONLINECOURSE.TAB_SCHOOL.SCHOOL_NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_SCHOOL.IMAGE_SIZE
     *
     * @return the value of ONLINECOURSE.TAB_SCHOOL.IMAGE_SIZE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getImageSize() {
        return imageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_SCHOOL.IMAGE_SIZE
     *
     * @param imageSize the value for ONLINECOURSE.TAB_SCHOOL.IMAGE_SIZE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize == null ? null : imageSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_SCHOOL.SCHOOL_PROFILE
     *
     * @return the value of ONLINECOURSE.TAB_SCHOOL.SCHOOL_PROFILE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getSchoolProfile() {
        return schoolProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_SCHOOL.SCHOOL_PROFILE
     *
     * @param schoolProfile the value for ONLINECOURSE.TAB_SCHOOL.SCHOOL_PROFILE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolProfile(String schoolProfile) {
        this.schoolProfile = schoolProfile == null ? null : schoolProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_SCHOOL.ISDELETE
     *
     * @return the value of ONLINECOURSE.TAB_SCHOOL.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_SCHOOL.ISDELETE
     *
     * @param isdelete the value for ONLINECOURSE.TAB_SCHOOL.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TAB_SCHOOL.PASSWORD
     *
     * @return the value of ONLINECOURSE.TAB_SCHOOL.PASSWORD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TAB_SCHOOL.PASSWORD
     *
     * @param password the value for ONLINECOURSE.TAB_SCHOOL.PASSWORD
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}