package com.oc.entity;

public class TeacherDegree extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEACHER_DEGREE.TEACHER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEACHER_DEGREE.DEGREE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer degreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEACHER_DEGREE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEACHER_DEGREE.TEACHER_ID
     *
     * @return the value of ONLINECOURSE.TEACHER_DEGREE.TEACHER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEACHER_DEGREE.TEACHER_ID
     *
     * @param teacherId the value for ONLINECOURSE.TEACHER_DEGREE.TEACHER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEACHER_DEGREE.DEGREE_ID
     *
     * @return the value of ONLINECOURSE.TEACHER_DEGREE.DEGREE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEACHER_DEGREE.DEGREE_ID
     *
     * @param degreeId the value for ONLINECOURSE.TEACHER_DEGREE.DEGREE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEACHER_DEGREE.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.TEACHER_DEGREE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEACHER_DEGREE.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.TEACHER_DEGREE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}