package com.oc.entity;

public class TestPaper extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.SUBJECT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.options
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String options;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.ANSWER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.TEST_PAPER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.ID
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.ID
     *
     * @param id the value for ONLINECOURSE.TEST_PAPER.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.NAME
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.NAME
     *
     * @param name the value for ONLINECOURSE.TEST_PAPER.NAME
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.COURSE_ID
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.COURSE_ID
     *
     * @param courseId the value for ONLINECOURSE.TEST_PAPER.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.SUBJECT
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.SUBJECT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.SUBJECT
     *
     * @param subject the value for ONLINECOURSE.TEST_PAPER.SUBJECT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.options
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.options
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.options
     *
     * @param options the value for ONLINECOURSE.TEST_PAPER.options
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.ANSWER
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.ANSWER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.ANSWER
     *
     * @param answer the value for ONLINECOURSE.TEST_PAPER.ANSWER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.ISDELETE
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.ISDELETE
     *
     * @param isdelete the value for ONLINECOURSE.TEST_PAPER.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.TEST_PAPER.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.TEST_PAPER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.TEST_PAPER.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.TEST_PAPER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}