package com.oc.entity;

public class UserHistorytestPaper extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.TEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer testPaper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.SCORE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.TOTAL
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ERROR_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer errorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ERRORS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String errors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.USER_ID
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.USER_ID
     *
     * @param userId the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.TEST_PAPER
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.TEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getTestPaper() {
        return testPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.TEST_PAPER
     *
     * @param testPaper the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.TEST_PAPER
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setTestPaper(Integer testPaper) {
        this.testPaper = testPaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.SCORE
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.SCORE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.SCORE
     *
     * @param score the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.SCORE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.TOTAL
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.TOTAL
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.TOTAL
     *
     * @param total the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.TOTAL
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ERROR_COUNT
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.ERROR_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getErrorCount() {
        return errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ERROR_COUNT
     *
     * @param errorCount the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.ERROR_COUNT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ERRORS
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.ERRORS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getErrors() {
        return errors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ERRORS
     *
     * @param errors the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.ERRORS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setErrors(String errors) {
        this.errors = errors == null ? null : errors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ISDELETE
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.ISDELETE
     *
     * @param isdelete the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.USER_HISTORYTEST_PAPER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_HISTORYTEST_PAPER.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.USER_HISTORYTEST_PAPER.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}