package com.oc.entity;

import java.util.Date;

public class UserVedio extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_VEDIO.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_VEDIO.VEDIO_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer vedioId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_VEDIO.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_VEDIO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_VEDIO.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Date updateDate;
    
    private CourseVideo courseVideo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_VEDIO.USER_ID
     *
     * @return the value of ONLINECOURSE.USER_VEDIO.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_VEDIO.USER_ID
     *
     * @param userId the value for ONLINECOURSE.USER_VEDIO.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_VEDIO.VEDIO_ID
     *
     * @return the value of ONLINECOURSE.USER_VEDIO.VEDIO_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getVedioId() {
        return vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_VEDIO.VEDIO_ID
     *
     * @param vedioId the value for ONLINECOURSE.USER_VEDIO.VEDIO_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setVedioId(Integer vedioId) {
        this.vedioId = vedioId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_VEDIO.STATUS
     *
     * @return the value of ONLINECOURSE.USER_VEDIO.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_VEDIO.STATUS
     *
     * @param status the value for ONLINECOURSE.USER_VEDIO.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_VEDIO.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.USER_VEDIO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_VEDIO.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.USER_VEDIO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_VEDIO.UPDATE_DATE
     *
     * @return the value of ONLINECOURSE.USER_VEDIO.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_VEDIO.UPDATE_DATE
     *
     * @param updateDate the value for ONLINECOURSE.USER_VEDIO.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

	public CourseVideo getCourseVideo() {
		return courseVideo;
	}

	public void setCourseVideo(CourseVideo courseVideo) {
		this.courseVideo = courseVideo;
	}
    
}