package com.oc.entity;

import java.util.Date;
import java.util.List;

public class UserMood extends BaseEntity{
	private List<UserMood> list;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_MOOD.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_MOOD.CONTENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_MOOD.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_MOOD.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_MOOD.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_MOOD.USER_ID
     *
     * @return the value of ONLINECOURSE.USER_MOOD.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_MOOD.USER_ID
     *
     * @param userId the value for ONLINECOURSE.USER_MOOD.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_MOOD.CONTENT
     *
     * @return the value of ONLINECOURSE.USER_MOOD.CONTENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_MOOD.CONTENT
     *
     * @param content the value for ONLINECOURSE.USER_MOOD.CONTENT
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_MOOD.UPDATE_DATE
     *
     * @return the value of ONLINECOURSE.USER_MOOD.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_MOOD.UPDATE_DATE
     *
     * @param updateDate the value for ONLINECOURSE.USER_MOOD.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_MOOD.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.USER_MOOD.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_MOOD.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.USER_MOOD.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_MOOD.ID
     *
     * @return the value of ONLINECOURSE.USER_MOOD.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_MOOD.ID
     *
     * @param id the value for ONLINECOURSE.USER_MOOD.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

	public List<UserMood> getList() {
		return list;
	}

	public void setList(List<UserMood> list) {
		this.list = list;
	}
    
}