package com.oc.entity;


public class UserInfo extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.ID
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.LOGIN_NAME
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.LOGIN_PWD
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.TYPE
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.EMAIL
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.HEAD_ADDRESS
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String headAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.STATUS
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.SELF_INTRODUCTION
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String selfIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.ISLOGIN
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer islogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.PHONE
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.QQ
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.HOBBY
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_INFO.SEX
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    private Integer sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.ID
     *
     * @return the value of ONLINECOURSE.USER_INFO.ID
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.ID
     *
     * @param id the value for ONLINECOURSE.USER_INFO.ID
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.LOGIN_NAME
     *
     * @return the value of ONLINECOURSE.USER_INFO.LOGIN_NAME
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.LOGIN_NAME
     *
     * @param loginName the value for ONLINECOURSE.USER_INFO.LOGIN_NAME
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.LOGIN_PWD
     *
     * @return the value of ONLINECOURSE.USER_INFO.LOGIN_PWD
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.LOGIN_PWD
     *
     * @param loginpwd the value for ONLINECOURSE.USER_INFO.LOGIN_PWD
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.TYPE
     *
     * @return the value of ONLINECOURSE.USER_INFO.TYPE
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.TYPE
     *
     * @param type the value for ONLINECOURSE.USER_INFO.TYPE
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.EMAIL
     *
     * @return the value of ONLINECOURSE.USER_INFO.EMAIL
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.EMAIL
     *
     * @param email the value for ONLINECOURSE.USER_INFO.EMAIL
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.HEAD_ADDRESS
     *
     * @return the value of ONLINECOURSE.USER_INFO.HEAD_ADDRESS
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getHeadAddress() {
        return headAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.HEAD_ADDRESS
     *
     * @param headAddress the value for ONLINECOURSE.USER_INFO.HEAD_ADDRESS
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setHeadAddress(String headAddress) {
        this.headAddress = headAddress == null ? null : headAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.STATUS
     *
     * @return the value of ONLINECOURSE.USER_INFO.STATUS
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.STATUS
     *
     * @param status the value for ONLINECOURSE.USER_INFO.STATUS
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.SELF_INTRODUCTION
     *
     * @return the value of ONLINECOURSE.USER_INFO.SELF_INTRODUCTION
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getSelfIntroduction() {
        return selfIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.SELF_INTRODUCTION
     *
     * @param selfIntroduction the value for ONLINECOURSE.USER_INFO.SELF_INTRODUCTION
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setSelfIntroduction(String selfIntroduction) {
        this.selfIntroduction = selfIntroduction == null ? null : selfIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.ISLOGIN
     *
     * @return the value of ONLINECOURSE.USER_INFO.ISLOGIN
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getIslogin() {
        return islogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.ISLOGIN
     *
     * @param islogin the value for ONLINECOURSE.USER_INFO.ISLOGIN
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setIslogin(Integer islogin) {
        this.islogin = islogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.PHONE
     *
     * @return the value of ONLINECOURSE.USER_INFO.PHONE
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.PHONE
     *
     * @param phone the value for ONLINECOURSE.USER_INFO.PHONE
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.QQ
     *
     * @return the value of ONLINECOURSE.USER_INFO.QQ
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.QQ
     *
     * @param qq the value for ONLINECOURSE.USER_INFO.QQ
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.HOBBY
     *
     * @return the value of ONLINECOURSE.USER_INFO.HOBBY
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.HOBBY
     *
     * @param hobby the value for ONLINECOURSE.USER_INFO.HOBBY
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.USER_INFO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.USER_INFO.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_INFO.SEX
     *
     * @return the value of ONLINECOURSE.USER_INFO.SEX
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_INFO.SEX
     *
     * @param sex the value for ONLINECOURSE.USER_INFO.SEX
     *
     * @mbggenerated Thu Apr 27 21:35:00 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }
}