package com.oc.entity;

import java.util.Date;

public class UserWords extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_WORDS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer id;
    
    private String words;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_WORDS.MESSAGE_SIDE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer messageSideId;
    private UserInfo messageSide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_WORDS.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_WORDS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_WORDS.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer userId;
    
    private UserInfo userinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_WORDS.ID
     *
     * @return the value of ONLINECOURSE.USER_WORDS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_WORDS.ID
     *
     * @param id the value for ONLINECOURSE.USER_WORDS.ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_WORDS.MESSAGE_SIDE_ID
     *
     * @return the value of ONLINECOURSE.USER_WORDS.MESSAGE_SIDE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getMessageSideId() {
        return messageSideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_WORDS.MESSAGE_SIDE_ID
     *
     * @param messageSideId the value for ONLINECOURSE.USER_WORDS.MESSAGE_SIDE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setMessageSideId(Integer messageSideId) {
        this.messageSideId = messageSideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_WORDS.UPDATE_DATE
     *
     * @return the value of ONLINECOURSE.USER_WORDS.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_WORDS.UPDATE_DATE
     *
     * @param updateDate the value for ONLINECOURSE.USER_WORDS.UPDATE_DATE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_WORDS.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.USER_WORDS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_WORDS.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.USER_WORDS.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_WORDS.USER_ID
     *
     * @return the value of ONLINECOURSE.USER_WORDS.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_WORDS.USER_ID
     *
     * @param userId the value for ONLINECOURSE.USER_WORDS.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

	public UserInfo getMessageSide() {
		return messageSide;
	}

	public void setMessageSide(UserInfo messageSide) {
		this.messageSide = messageSide;
	}

	public UserInfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(UserInfo userinfo) {
		this.userinfo = userinfo;
	}

	public String getWords() {
		return words;
	}

	public void setWords(String words) {
		this.words = words;
	}
    
}