package com.oc.entity;

public class UserCourse extends BaseEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_COURSE.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_COURSE.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_COURSE.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_COURSE.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ONLINECOURSE.USER_COURSE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    private Integer schoolId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_COURSE.USER_ID
     *
     * @return the value of ONLINECOURSE.USER_COURSE.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_COURSE.USER_ID
     *
     * @param userId the value for ONLINECOURSE.USER_COURSE.USER_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_COURSE.COURSE_ID
     *
     * @return the value of ONLINECOURSE.USER_COURSE.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_COURSE.COURSE_ID
     *
     * @param courseId the value for ONLINECOURSE.USER_COURSE.COURSE_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_COURSE.STATUS
     *
     * @return the value of ONLINECOURSE.USER_COURSE.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_COURSE.STATUS
     *
     * @param status the value for ONLINECOURSE.USER_COURSE.STATUS
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_COURSE.ISDELETE
     *
     * @return the value of ONLINECOURSE.USER_COURSE.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_COURSE.ISDELETE
     *
     * @param isdelete the value for ONLINECOURSE.USER_COURSE.ISDELETE
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ONLINECOURSE.USER_COURSE.SCHOOL_ID
     *
     * @return the value of ONLINECOURSE.USER_COURSE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ONLINECOURSE.USER_COURSE.SCHOOL_ID
     *
     * @param schoolId the value for ONLINECOURSE.USER_COURSE.SCHOOL_ID
     *
     * @mbggenerated Thu Apr 27 22:12:38 CST 2017
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}